import os
import json
import feedparser
from datetime import datetime
from google import genai

# --- 1. SETUP & CONFIG ---
try:
    client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))
except Exception as e:
    print(f"Error: GEMINI_API_KEY not found or invalid. {e}")
    exit(1)

# You can change this RSS URL to any tech/AI news source
RSS_FEED_URL = "https://news.google.com/rss?q=artificial+intelligence+deep+tech&hl=en-US&gl=US&ceid=US:en"

def fetch_news():
    print("Fetching RSS Feed...")
    feed = feedparser.parse(RSS_FEED_URL)
    articles = []
    # Grab the top 8 articles for a good variety
    for entry in feed.entries[:8]:
        articles.append({
            "title": entry.title,
            "link": entry.link,
            "published": getattr(entry, 'published', 'Date Unknown')
        })
    return articles

def summarize_news(articles):
    print("Generating AI Insights with Gemini 2.0 Flash...")
    # Formatting the prompt to get a clean, professional summary
    headlines = "\n".join([f"- {a['title']}" for a in articles])
    prompt = f"""
    You are UnicrisAI News Bot. 
    Summarize the following tech headlines into a concise, 3-bullet point executive summary 
    highlighting the most important trends. Use a professional yet forward-thinking tone.
    
    Headlines:
    {headlines}
    """
    
    try:
        response = client.models.generate_content(
            model="gemini-2.0-flash", 
            contents=prompt
        )
        return response.text
    except Exception as e:
        print(f"Gemini API Error: {e}")
        return "Insight generation currently unavailable."

def update_files(summary, articles):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    # --- Update data.json ---
    data_payload = {
        "last_update": timestamp,
        "summary": summary,
        "articles": articles
    }
    with open("data.json", "w", encoding="utf-8") as f:
        json.dump(data_payload, f, indent=4)

    # --- Update index.html (The Daily View) ---
    html_template = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>UnicrisAI Daily News</title>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; }}
            h1 {{ color: #1a73e8; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
            .summary {{ background: #f8f9fa; padding: 20px; border-radius: 8px; border-left: 5px solid #1a73e8; margin-bottom: 30px; }}
            .links {{ list-style: none; padding: 0; }}
            .links li {{ margin-bottom: 10px; }}
            a {{ color: #1a73e8; text-decoration: none; }}
            a:hover {{ text-decoration: underline; }}
            footer {{ margin-top: 50px; font-size: 0.8em; color: #777; }}
        </style>
    </head>
    <body>
        <h1>UnicrisAI News Update</h1>
        <p><strong>Last Updated:</strong> {timestamp} (UTC)</p>
        
        <div class="summary">
            <h3>🤖 AI Executive Summary</h3>
            {summary.replace('\n', '<br>')}
        </div>

        <h3>Latest Sources</h3>
        <ul class="links">
            {"".join([f'<li><a href="{a["link"]}" target="_blank">{a["title"]}</a></li>' for a in articles])}
        </ul>

        <footer>
            <p>Generated by UnicrisAI Innovation Engine | <a href="archive.html">Browse Archive</a></p>
        </footer>
    </body>
    </html>
    """
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_template)

    # --- Update archive.html (The Running Log) ---
    # We check if it exists; if not, we create it with a header
    if not os.path.exists("archive.html"):
        with open("archive.html", "w") as f:
            f.write("<h1>UnicrisAI News Archive</h1><hr>\n")
            
    with open("archive.html", "a", encoding="utf-8") as f:
        f.write(f"<div><small>{timestamp}</small> - {summary[:150]}... <a href='index.html'>Read More</a></div><hr>\n")

if __name__ == "__main__":
    items = fetch_news()
    if items:
        report = summarize_news(items)
        update_files(report, items)
        print("Success: Files updated.")
    else:
        print("No news found today.")
